name: dart_ng_forms
description: Reactive Forms architecture in Flutter inspired by Angular's FormGroup/FormControl pattern and integration with TextEditingController.
version: 1.5.4
repository: https://github.com/mikaelbotassi/dart_ng_forms.git
issue_tracker: https://github.com/mikaelbotassi/dart_ng_forms/issues
homepage: https://github.com/mikaelbotassi/dart_ng_forms

topics:
  - forms
  - state-management
  - validation
  - flutter
  - reactive-forms

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  result_dart: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
